### ISSUE TITLE
how to add blueprint to the experiment?

### ISSUE THREAD

**Issue by amaatouq** [empiricaly/create-empirica-app#4]
I tried `meteor npm install --save @blueprintjs/core` and then using the old UI components (i.e., using blueprint components) but nothing format-wise is happening!

**Comment by npaton** [comment]
If you are using a version of Blueprint other than v3, you need to add the Blueprint CSS to your project.

I you can, you might as well move to Blueprint v3. If make sure you use React components, which will automatically use the right CSS classes automatically, rather than creating elements and applying classes manually. (https://blueprintjs.com/docs/#core/classes)

`meteor npm install @blueprintjs/core@latest --save`

But if you have a lot of code in Blueprint v1 or v2, install the right version:

```
meteor npm install @blueprintjs/core@"<3.0.0 --save"
meteor npm install @blueprintjs/core@"<2.0.0 --save"
```

Then import the css into your client JS somewhere, for example in `client/main.js`:

```js
import "normalize.css/normalize.css";
import "@blueprintjs/core/dist/blueprint.css";
```

**Comment by amaatouq** [comment]
Hmm it seems that one can use `blueprint^3` and not change much by replacing `pt-` with `pb3-` in the `className` .. this worked fine for me after:
```
import "@blueprintjs/icons/lib/css/blueprint-icons.css";
import "@blueprintjs/core/lib/css/blueprint.css";
```
The problem is that the icons are not imported (I just get an empty square). I am not sure how to import the icons in blueprint 3

**Comment by npaton** [comment]
< BP v3, icons were loaded through a webfont. Since BP v3, icons are imported from SVG. Which is why it's preferable to use the React components, which handle all the loading cleanly. V3 does still support the webfont as a fallback, when just using CSS classes. But you need to make the font available to load in you public folder. Copy them from `node_modules/@blueprint/core/...` into `public/resources/...` (sorry, I don't have the full paths on hand). I believe Empirica classic (pre packaging) did do this, if you want to take a look.

**Comment by amaatouq** [comment]
works!
